# Generated by Django 4.1.3 on 2022-12-06 02:05

from django.db import migrations, transaction, models
import random


def forwards_func(apps, schema_editor):
    departments = apps.get_model('employees_list', 'Department')
    employees = apps.get_model('employees_list', 'Employee')

    for i in range(1, 11):
        departments.objects.create(name=f'Отдел {i}')

    for i in range(11, 101):
        dep = departments.objects.get(id=random.randint(1, 10))
        departments.objects.create(name=f'Отдел {i}', head_department=dep)

    for i in range(101, 1001):
        dep = departments.objects.get(id=random.randint(11, 100))
        departments.objects.create(name=f'Отдел {i}', head_department=dep)

    for i in range(1001, 5001):
        dep = departments.objects.get(id=random.randint(101, 1000))
        departments.objects.create(name=f'Отдел {i}', head_department=dep)

    with open('employees.txt', 'r') as f:
        for line in f.readlines():
            dep = departments.objects.get(id=random.randint(1001, 5000))
            data = line.split(',')
            employees.objects.create(
                name=data[0],
                job_started=data[1],
                position=data[2],
                salary=data[3],
                department=dep
            )


class Migration(migrations.Migration):

    dependencies = [
        ('employees_list', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
